PRONEXEL_WEB/Controllers/ThemeManagementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PRONEXEL_Business.Repositories;
using System.Threading.Tasks;

namespace PRONEXEL_WEB.Controllers
{

    [Authorize(Roles = "SuperAdmin")]
    public class ThemeManagementController : Controller
    {
        private readonly ThemeRepo _themeRepo;
        public ThemeManagementController(ThemeRepo themeRepo)
        {
            this._themeRepo = themeRepo;
        }
        [HttpGet]
        public async Task<IActionResult> DarkMood()
        {
            var res = await _themeRepo.GetActiveColor();
            ViewBag.res=res;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> DarkMood(string Color)
        {
            var res = await _themeRepo.UpdateThemeColor(Color);
            ViewBag.res=res;
            return View();
        }
        [AllowAnonymous]
        [HttpGet]
        public async Task<JsonResult> GetActiveColor()
        {
            var res = await _themeRepo.GetActiveColor();
            return Json(res);
        }
    }
}

PRONEXEL_WEB/Views/ThemeManagement/DarkMood.cshtml
@{
    ViewData["Title"] = "DarkMood";
}
<div class="nk-block nk-block-lg">

    <div class="card card-bordered">
        <div class="card-inner">
            <div class="card-head">
                <h5 class="card-title">Manage Theme</h5>
            </div>
            <form id="userForm" asp-action="DarkMood" asp-controller="ThemeManagement" method="post">
                <div class="row g-4">


                    <!-- Role -->
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-label" for="user-role">Dark Theme</label>
                            <div class="form-control-wrap">
                                <select name="Color" class="form-control" id="user-role" required>
                                    @if (ViewBag.res == "Normal")
                                    {
                                        <option value="Normal" selected>Normal</option>
                                        <option value="DarkMood">DarkMood</option>
                                    }
                                    else
                                    {
                                        <option value="Normal" >Normal</option>
                                        <option value="DarkMood" selected>DarkMood</option>
                                    }

                                
                                </select>
                            </div>
                        </div>
                    </div>
                    <!-- Submit -->
                    <div class="col-12">
                        <div class="form-group">
                            <button type="submit" class="btn btn-lg btn-primary">Save Information</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>